typography_spectrum: 0.25811
color:
  brandColors:
    - '#e8e3d0'
    - '#000000'
    - '#b29f91'
    - '#443635'
    - '#705c5d'
  brandStrength: 0.5625
  lightness: 0.7282201738562435
  saturation: 0.375
  rhythmicContrast: 0.2940610114019364
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 1
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Andrea Porcù
  email: andrew@atoman.net
name: ATOMAN
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: ATTO BAGS
    url: 'https://www.attobags.com/'
    type: external
favicon: null
title: ATOMAN dot NET
description: Andrea Porcu personal website
purpose: []
