name: ATOMAN
favicon: null
layout_spectrum: 1
typography_spectrum: 0.25811
author:
  name: Andrea Porcù
  email: andrew@atoman.net
title: ATOMAN dot NET
description: Andrea Porcu personal website
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e8e3d0'
    - '#000000'
    - '#b29f91'
    - '#443635'
    - '#705c5d'
  brandStrength: 0.5625
  lightness: 0.7282201738562435
  saturation: 0.375
  rhythmicContrast: 0.2940610114019364
purpose: []
