typography_spectrum: 0.7547024479135871
color:
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
  brandStrength: 0.4677601952571422
  lightness: 0.8876005592755973
  saturation: 0.3493641063105315
  rhythmicContrast: 0.024251872906461358
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.8434741860255599
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Andrea Porcù
  email: andrew@atoman.net
name: ATOMAN
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: ATTO BAGS
    url: 'https://www.attobags.com/'
    type: external
favicon: null
title: ATOMAN dot NET
description: Andrea Porcu personal website
purpose: []
