name: ATOMAN
favicon: null
layout_spectrum: 0.14474
typography_spectrum: 0.55471
author:
  name: Andrea Porcù
  email: andrew@atoman.net
title: ATOMAN dot NET
description: Andrea Porcu personal website
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.5625
  lightness: 0.7282201738562435
  saturation: 0.375
  rhythmicContrast: 0.2940610114019364
purpose: []
